# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory
WORKDIR /app

# Copy your script into the container
COPY main.py .

# Run your Python script
CMD ["python", "main.py"]
